name: nocterm_lints
description: >- 
  Set of Assists for Nocterm development, you can use same DX as you do with Flutter, but in Nocterm projects.
version: 0.5.0
repository: https://github.com/zoocityboy/nocterm_lints
homepage: https://github.com/zoocityboy/nocterm_lints
issue_tracker: https://github.com/zoocityboy/nocterm_lints/issues
topics:
  - linter
  - assists
  - analyzer
  - nocterm
environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  _fe_analyzer_shared: ^94.0.0
  analysis_server_plugin: '>=0.3.8 <0.4.0'
  analyzer: '>=10.0.2 <11.0.0'
  analyzer_plugin: '>=0.14.2 <0.15.0'
  collection: ^1.19.0
  nocterm: '>=0.5.0 <0.6.0'
  path: ^1.9.1

dev_dependencies:
  analyzer_testing: ^0.1.10
  hooksman: ^3.1.2
  lints: ^6.1.0
  meta: any
  test: ^1.28.0
  test_reflective_loader: ^0.4.0
